from unittest import mock


from wpipe_mcp import server


def test_blueprints_have_real_newlines():
    text = server.get_wpipe_architect_blueprints()
    assert "WPIPE EXPERT BLUEPRINTS" in text
    assert "Advanced State Pattern" in text
    assert "High-Performance Pipeline Pattern" in text
    assert "\n" in text
    assert "\\n" not in text


def test_manual_contains_guides():
    text = server.get_wpipe_architect_manual()
    assert "WPIPE ARCHITECT MANUAL" in text
    assert "PROJECT STRUCTURE RULES" in text
    assert "CORE RULES" in text
    assert "REFACTORING A MONOLITH TO WPIPE" in text
    assert "mermaid" in text
    assert "Generated by WPipe MCP by wisrovi" in text


def test_search_wpipe_step_returns_results():
    results = [
        {"origin": "Official", "func_name": "vision_yolo", "description": "YOLO vision step", "namespace": "wpipe_plugins.vision"},
        {"origin": "Community", "func_name": "csv_reader", "description": "CSV reader step", "namespace": "wpipe_plugins"},
    ]
    catalog_mock = mock.MagicMock()
    catalog_mock.search.return_value = results
    with mock.patch.object(server, "get_catalog", return_value=catalog_mock):
        text = server.search_wpipe_step("yolo")
    assert "vision_yolo" in text
    assert "Official" in text
    assert "Community" in text


def test_search_wpipe_step_no_results():
    catalog_mock = mock.MagicMock()
    catalog_mock.search.return_value = []
    with mock.patch.object(server, "get_catalog", return_value=catalog_mock):
        text = server.search_wpipe_step("zzz_nope")
    assert "No custom step matching 'zzz_nope' was found" in text


def test_deploy_wpipe_scaffolding_relative_path_rejected():
    text = server.deploy_wpipe_scaffolding("relative/path")
    assert text.startswith("Error:")
    assert "absolute path" in text


def test_deploy_wpipe_scaffolding_creates_project(tmp_path):
    target = str(tmp_path / "deployed")
    result = server.deploy_wpipe_scaffolding(target, project_name="MyPipe", pipeline_type="standard")
    assert result.startswith("Success:")
    assert "MyPipe" in result
    assert (tmp_path / "deployed" / "main.py").exists()
    assert (tmp_path / "deployed" / "dto" / "process_context.py").exists()
    assert (tmp_path / "deployed" / "states" / "process_step.py").exists()


def test_deploy_wpipe_scaffolding_exception_returns_error(tmp_path):
    target = str(tmp_path / "blocked")
    with mock.patch.object(server.TemplateGenerator, "get_folders", side_effect=OSError("disk full")):
        text = server.deploy_wpipe_scaffolding(target)
    assert text == "Error: disk full"


def test_run_stdio_uses_stdio_transport():
    with mock.patch.object(server.mcp, "run") as mock_run:
        server.run_stdio()
    mock_run.assert_called_once_with(transport="stdio")


def test_run_sse_uses_sse_transport():
    with mock.patch.object(server.mcp, "run") as mock_run:
        server.run_sse()
    mock_run.assert_called_once_with(transport="sse")


def test_print_config_to_stdout(capsys):
    server.print_config(write_file=False)
    captured = capsys.readouterr()
    assert "wpipe-mcp" in captured.out
    assert "QUICK INSTALL COMMANDS" in captured.out


def test_print_config_saves_file(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    server.print_config(write_file=True)
    assert (tmp_path / ".agents" / "wpipe-mcp.json").exists()


def test_main_config_saves_file(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    monkeypatch.setattr(server.sys, "argv", ["wpipe-mcp", "config"])
    server.main()
    assert (tmp_path / ".agents" / "wpipe-mcp.json").exists()


def test_main_run_uses_stdio(monkeypatch):
    monkeypatch.setattr(server.sys, "argv", ["wpipe-mcp", "run"])
    with mock.patch.object(server.mcp, "run") as mock_run:
        server.main()
    mock_run.assert_called_once_with(transport="stdio")


def test_deploy_wpipe_scaffolding_microservice_with_tests(tmp_path):
    target = str(tmp_path / "micro_with")
    result = server.deploy_wpipe_scaffolding(
        target, project_name="MicroApp", pipeline_type="microservice", include_tests=True
    )
    assert result.startswith("Success:")
    assert (tmp_path / "micro_with" / "app" / "main.py").exists()
    assert (tmp_path / "micro_with" / "app" / "pipelines.py").exists()
    assert (tmp_path / "micro_with" / "app" / "dto" / "context.py").exists()
    assert (tmp_path / "micro_with" / "app" / "test" / "test_dto.py").exists()
    assert not (tmp_path / "micro_with" / "app" / "test" / "README.md").exists()


def test_deploy_wpipe_scaffolding_microservice_without_tests(tmp_path):
    target = str(tmp_path / "micro_without")
    result = server.deploy_wpipe_scaffolding(
        target, project_name="MicroApp", pipeline_type="microservice", include_tests=False
    )
    assert result.startswith("Success:")
    assert (tmp_path / "micro_without" / "app" / "main.py").exists()
    assert (tmp_path / "micro_without" / "app" / "test" / "README.md").exists()
    assert not (tmp_path / "micro_without" / "app" / "test" / "test_dto.py").exists()


def test_validate_wpipe_project_fully_compliant(tmp_path):
    target = str(tmp_path / "compliant_project")
    server.deploy_wpipe_scaffolding(
        target, project_name="CompApp", pipeline_type="microservice", include_tests=True
    )
    report = server.validate_wpipe_project(target)
    assert "Compliance Status: Fully Compliant" in report
    assert "Found main entrypoint" in report
    assert "Found directory: 'dto/'" in report


def test_validate_wpipe_project_violations(tmp_path):
    target = str(tmp_path / "violating_project")
    server.deploy_wpipe_scaffolding(
        target, project_name="ViolatingApp", pipeline_type="microservice", include_tests=True
    )
    
    # 1. Add a @step file outside states
    wrong_step = tmp_path / "violating_project" / "app" / "utils" / "wrong_step.py"
    wrong_step.write_text("from wpipe import step\n@step()\nclass WrongStep:\n    pass\n")
    
    # 2. Add a BaseModel file outside dto
    wrong_model = tmp_path / "violating_project" / "app" / "services" / "wrong_model.py"
    wrong_model.write_text("from pydantic import BaseModel\nclass MyWrongModel(BaseModel):\n    pass\n")
    
    report = server.validate_wpipe_project(target)
    assert "Architectural violation: WPipe '@step' class defined in" in report
    assert "Architectural violation: Pydantic 'BaseModel' defined in" in report
    assert "wrong_step.py" in report
    assert "wrong_model.py" in report


def test_document_wpipe_project(tmp_path):
    target = str(tmp_path / "doc_project")
    server.deploy_wpipe_scaffolding(
        target, project_name="DocApp", pipeline_type="microservice", include_tests=True
    )
    
    report = server.document_wpipe_project(target, write_to_readme=True)
    assert "Success: Technical execution flow documented successfully." in report
    assert "InferenciaStep" in report
    assert "graph TD" in report
    
    readme_file = tmp_path / "doc_project" / "README.md"
    assert readme_file.exists()
    content = readme_file.read_text()
    assert "## 🦅 WPipe Execution Flow" in content
    assert "<!-- WPIPE_FLOW_START -->" in content
    assert "<!-- WPIPE_FLOW_END -->" in content


def test_refactor_monolith_to_wpipe(tmp_path):
    # Create a mock monolith
    monolith = tmp_path / "monolith.py"
    monolith.write_text(
        "def load_images(batch_size, folder_path):\n"
        "    return []\n\n"
        "def run_prediction(model_weights, image_list):\n"
        "    return {}\n"
    )
    
    target = str(tmp_path / "refactored")
    result = server.refactor_monolith_to_wpipe(str(monolith), target)
    assert result.startswith("Success:")
    
    # Check that app folders and files were created
    assert (tmp_path / "refactored" / "app" / "dto" / "context.py").exists()
    assert (tmp_path / "refactored" / "app" / "states" / "step_0_load_images.py").exists()
    assert (tmp_path / "refactored" / "app" / "states" / "step_1_run_prediction.py").exists()
    assert (tmp_path / "refactored" / "app" / "pipelines.py").exists()
    assert (tmp_path / "refactored" / "app" / "main.py").exists()
    
    # Check DTO contains extracted args
    dto_content = (tmp_path / "refactored" / "app" / "dto" / "context.py").read_text()
    assert "batch_size" in dto_content
    assert "folder_path" in dto_content
    assert "model_weights" in dto_content
    assert "image_list" in dto_content
    
    # Check README has generated flow
    readme_content = (tmp_path / "refactored" / "README.md").read_text()
    assert "LoadImagesStep" in readme_content
    assert "RunPredictionStep" in readme_content
