# Advanced scaffolding templates for professional WPipe development

class TemplateGenerator:
    """Provides professional boilerplate for WPipe projects following wisrovi standards."""

    @staticmethod
    def get_supported_types() -> list:
        return ["standard", "ai_vision_mlops"]

    @staticmethod
    def get_folders(pipeline_type: str) -> list:
        if pipeline_type == "ai_vision_mlops":
            return ["config", "src", "src/inference", "src/training", "src/training/tasks", "src/states", "datasets", "tests", ".wpipe"]
        return ["config", "src", "src/steps", "src/states", "tests", ".wpipe"]

    @staticmethod
    def get_files_blueprint(pipeline_type: str, project_name: str = "wpipe_project") -> dict:
        """Returns filenames and their professional template content."""
        
        # Professional Class-based State Template
        state_template = (
            "from wpipe import step, to_obj\n"
            "from wpipe.timeout import timeout_sync\n"
            "from typing import Any\n"
            "from pydantic import BaseModel\n\n"
            "class ProcessDataContext(BaseModel):\n"
            "    \"\"\"Typed context for the step.\"\"\"\n"
            "    field: str\n\n"
            "@step(\n"
            "    name=\"ProcessData\",\n"
            "    version=\"v1.0\",\n"
            "    timeout=10,\n"
            "    description=\"Professional data processing step\",\n"
            "    tags=[\"custom\", \"processing\"],\n"
            "    retry_count=3,\n"
            "    retry_delay=0.01,\n"
            ")\n"
            "class ProcessDataStep:\n"
            "    \"\"\"\n"
            "    Advanced WPipe State: ProcessData\n"
            "    Generated by wpipe-mcp Architect.\n"
            "    \"\"\"\n"
            "    \n"
            "    def __init__(self, config: str = \"default_value\"):\n"
            "        self.config = config\n\n"
            "    @timeout_sync(seconds=2)\n"
            "    @to_obj(ProcessDataContext)\n"
            "    def __call__(self, context: Any) -> Any:\n"
            "        # Professional logic here\n"
            "        print(f\"🚀 Executing ProcessData with config: {self.config}\")\n"
            "        return context\n"
        )

        # Main Pipeline Template
        pipeline_template = (
            "import os\n"
            "from wdecorators import time_execution\n"
            "from wpipe import Pipeline, ResourceMonitor, TaskTimer\n"
            "from wpipe.exception.api_error import ProcessError\n"
            "from src.states.process_step import ProcessDataStep\n\n"
            "def run_pipeline():\n"
            "    db_path = \"output/tracking.db\"  # Metrics, events, and forensics\n"
            "    config_dir = (\"configs\",)      # Optional YAML/JSON configs\n\n"
            "    pipeline = Pipeline(\n"
            "        pipeline_name=\"{name}\",\n"
            "        pipeline_version=\"1.0.0\",\n"
            "        tracking_db=db_path,\n"
            "        config_dir=config_dir,\n"
            "        verbose=False,\n"
            "        max_retries=3,\n"
            "        retry_delay=0.5,\n"
            "        retry_on_exceptions=(RuntimeError,),\n"
            "        collect_system_metrics=True,\n"
            "        show_progress=True\n"
            "    )\n\n"
            "    pipeline.set_steps([\n"
            "        ProcessDataStep(config=\"prod\")\n"
            "    ])\n\n"
            "    initial_data = {{\"field\": \"init\"}}\n\n"
            "    try:\n"
            "        with ResourceMonitor(\"{name}_monitor\") as monitor:\n"
            "            with TaskTimer(\"{name}_timer\", timeout_seconds=900) as timer:\n\n"
            "                @time_execution\n"
            "                def run():\n"
            "                    return pipeline.run(initial_data)\n\n"
            "                result = run()\n"
            "                \n"
            "        summary = monitor.get_summary()\n"
            "        print(f\"Peak RAM: {{summary['peak_ram_mb']}} MB\")\n"
            "        print(f\"Avg CPU: {{summary['avg_cpu_percent']}}%\")\n"
            "        print(f\"Total time: {{timer.elapsed_seconds:.2f}}s\")\n"
            "        return result\n"
            "    except ProcessError as e:\n"
            "        print(f\"Error occurred: {{e}}\")\n\n"
            "if __name__ == \"__main__\":\n"
            "    run_pipeline()\n"
        ).format(name=project_name)

        blueprints = {
            "requirements.txt": "wpipe>=1.0.0\nwdecorators>=2.0.0\npydantic>=2.0.0\n",
            "README.md": f"# {project_name.upper()}\n\nProfessional architecture built with **wpipe**.\n",
            "src/states/__init__.py": "from .process_step import ProcessDataStep\n",
            "src/states/process_step.py": state_template,
            "main.py": pipeline_template,
            "wpipe.config.json": '{\n  "enableBackupFile": true,\n  "maxSearchFiles": 500\n}\n'
        }

        if pipeline_type == "ai_vision_mlops":
            blueprints["requirements.txt"] += "wyolo>=1.0.0\nwtrain>=1.0.0\ncelery>=5.3.0\n"
            # Add vision specific boilerplate...
            
        return blueprints
